apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-hashbang-dev
  namespace: hash-bang
spec:
  secretName: whoami-hashbang-dev
  dnsNames:
    - whoami.hash-bang.dev
    - www.whoami.hash-bang.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
